name: dbt_poseidon
version: '1.0.0'

profile: dbt_poseidon

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  dbt_poseidon:
    staging:
      +materialized: ephemeral
      +schema: staging

    intermediate:
      +materialized: view
      +schema: intermediate

    marts:
      +materialized: table
      +schema: marts

seeds:
  dbt_poseidon:
    schema: staging
